# Generated by Django 4.2.4 on 2023-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='svg_image',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
